### ISSUE TITLE
Find LPPs

### ISSUE THREAD

**Issue by da-the-dev** [da-the-dev/simplex#1]
We need to have 2-3 LPPs to understand the algorithm and to test it

**Comment by KhairullinaAlsu** [comment]
[задачи.docx](https://github.com/da-the-dev/simplex/files/12674623/default.docx)

**Comment by KhairullinaAlsu** [comment]
две задачи на максимум

**Comment by da-the-dev** [comment]
> две задачи на максимум

Отлично! Очень красиво сделано!

**Comment by natagapova** [comment]
капец надеюсь норм [Optimization LPP with Simplex Method examples ebf6befa03b3445fbf9086359eedafc0.pdf](https://github.com/da-the-dev/simplex/files/12678527/Optimization.LPP.with.Simplex.Method.examples.ebf6befa03b3445fbf9086359eedafc0.pdf)
